### ISSUE TITLE
A TabController was used after being disposed.

### ISSUE THREAD

**Issue by keluokeda** [gbrvalerio/carousel#9]
Unhandled exception when activity finish
`A TabController was used after being disposed.
Once you have called dispose() on a TabController, it can no longer be used.
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:61:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:67:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:155:12)
#3      TabController._changeIndex.<anonymous closure> (package:flutter/src/material/tab_controller.dart:124:11)
#4      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:390:15)
#5      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#6      _FutureListener.handleError (dart:async/future_impl.dart:147:20)
#7      Future._propagateToListeners.handleError (dart:async/future_impl.dart:650:47)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:24)
#9   <…>`

**Comment by rdcoder33** [comment]
I have the same problem, did anyone found any solution.

**Comment by drdedou** [comment]
you should be used Tab Controller in your Tab Bar
and disposed see this https://api.flutter.dev/flutter/material/TabController-class.html
